itm327:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: TRAINING_ROLE
      database: SNOWBEARAIR_DB
      schema: RAW
      warehouse: ANIMAL_TASK_WH
    prod:
      type: snowflake
      account: 'not needed'
      user: 'not needed'
      role: TRAINING_ROLE
      database: SNOWBEARAIR_DB
      schema: MODELED
      warehouse: ANIMAL_TASK_WH
