SELECT DISTINCT
    CAST(DATETIME AS DATE) AS CALENDAR_DATE,
    DAY(CAST(DATETIME AS DATE)) AS DAY_NUM_IN_MONTH,
    DAYNAME(CAST(DATETIME AS DATE)) AS DAY_NAME,
    DAYOFWEEK(CAST(DATETIME AS DATE)) AS DAY_OF_WEEK_NUM,
    WEEK(CAST(DATETIME AS DATE)) AS WEEK_NUM,
    MONTH(CAST(DATETIME AS DATE)) AS MONTH_NUM,
    MONTHNAME(CAST(DATETIME AS DATE)) AS MONTH_NAME,
    QUARTER(CAST(DATETIME AS DATE)) AS QUARTER,
    YEAR(CAST(DATETIME AS DATE)) AS YEAR,
    CASE WHEN DAYNAME(CAST(DATETIME AS DATE)) IN ('Sat','Sun') THEN TRUE ELSE FALSE END AS IS_WEEKEND_FLAG,
    CASE WHEN DAYNAME(CAST(DATETIME AS DATE)) NOT IN ('Sat','Sun') THEN TRUE ELSE FALSE END AS IS_WEEKDAY_FLAG
FROM {{ source('raw', 'MONGO_DAG_OLIPHANT_J') }}